package cn.edu.henu.xsg.model;

import cn.edu.henu.xsg.model.base.BaseReservation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reservation extends BaseReservation<Reservation> {
	public static final Reservation dao = new Reservation().dao();
}
