package cn.edu.henu.xsg.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseReservation<M extends BaseReservation<M>> extends Model<M> implements IBean {

	public M setGuid(java.lang.String guid) {
		set("guid", guid);
		return (M)this;
	}

	public java.lang.String getGuid() {
		return get("guid");
	}

	public M setUnit(java.lang.String unit) {
		set("unit", unit);
		return (M)this;
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

	public M setContacts(java.lang.String contacts) {
		set("contacts", contacts);
		return (M)this;
	}

	public java.lang.String getContacts() {
		return get("contacts");
	}

	public M setPhoneNum(java.lang.String phoneNum) {
		set("phone_num", phoneNum);
		return (M)this;
	}

	public java.lang.String getPhoneNum() {
		return get("phone_num");
	}

	public M setVisitDate(java.util.Date visitDate) {
		set("visit_date", visitDate);
		return (M)this;
	}

	public java.util.Date getVisitDate() {
		return get("visit_date");
	}

	public M setVisitTime(java.lang.Integer visitTime) {
		set("visit_time", visitTime);
		return (M)this;
	}

	public java.lang.Integer getVisitTime() {
		return get("visit_time");
	}

	public M setVisitNum(java.lang.Integer visitNum) {
		set("visit_num", visitNum);
		return (M)this;
	}

	public java.lang.Integer getVisitNum() {
		return get("visit_num");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setIsDeleted(java.lang.String isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}

	public java.lang.String getIsDeleted() {
		return get("is_deleted");
	}

}
